# Checks file and directory names against ls-lint rules.
#
# The configuration is generated from `settings`: shared `rules`, scoped
# overrides in `scopes`, and an `ignore` list. ls-lint replaces rather than
# merges the rules of a scoped block, so each scope is rendered as the
# shared rules with its own keys on top, and a scope states only what it
# changes. `configFile` uses an existing `.ls-lint.yml` instead.
pkgs: {
  config,
  lib,
  ...
}: let
  cfg = config.settings;
  rule = lib.types.nullOr lib.types.str;
  # A rule set to null is dropped, so a scope can stop checking an extension
  # the shared rules check.
  present = lib.filterAttrs (_: v: v != null);
  generated = {
    ls = present cfg.rules // lib.mapAttrs (_: scope: present (cfg.rules // scope)) cfg.scopes;
    inherit (cfg) ignore;
  };
in {
  options.settings = {
    rules = lib.mkOption {
      type = lib.types.attrsOf rule;
      description = ''
        The rules for the whole tree, keyed by `.dir` or an extension such as
        `.ts`. ls-lint keys an extension off everything after a name's first
        dot, so a rule governs single-dot names only and `foo.test.ts` stays
        unchecked.
      '';
    };

    scopes = lib.mkOption {
      type = lib.types.attrsOf (lib.types.attrsOf rule);
      default = {};
      example = {
        "libraries/rust".".dir" = "snake_case | kebab-case";
      };
      description = "Rules for a path, merged over `rules`.";
    };

    ignore = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      description = ''
        Paths ls-lint skips. It reads no `.gitignore`, so every build output and
        tool cache a working checkout accumulates has to be here. A repository's
        entries are added to devkit's.
      '';
    };

    configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = ".ls-lint.yml";
      description = "An ls-lint configuration in the repository, relative to its root, used instead of the generated one.";
    };

    generatedConfig = lib.mkOption {
      type = lib.types.path;
      readOnly = true;
      description = "The configuration rendered from `rules`, `scopes` and `ignore`.";
    };
  };

  config = {
    settings = {
      rules = lib.mapAttrs (_: lib.mkDefault) {
        ".dir" = "kebab-case";
        ".ts" = "kebab-case";
        ".tsx" = "kebab-case";
        ".js" = "kebab-case";
        ".css" = "kebab-case";
        ".json" = "kebab-case";
        ".gql" = "kebab-case";
        ".nix" = "kebab-case";
        ".sh" = "kebab-case";
        # A module's file or directory name is a Rust identifier, which cannot
        # hold a hyphen, while a binary's entry file is named like any other.
        ".rs" = "snake_case | kebab-case";
      };
      ignore = [
        "**/.git"
        "**/.github"
        "**/.yarn"
        "**/.cargo"
        "**/.direnv"
        "**/.devenv"
        "**/.cache"
        "**/.claude"
        "**/.vscode"
        "**/node_modules"
        "**/target"
        "**/result"
        "**/dist"
        "**/cdk.out"
        "**/__snapshots__"
        # Generated by crate2nix, not named by hand.
        "**/Cargo.json"
      ];
      generatedConfig = (pkgs.formats.yaml {}).generate "ls-lint.yml" generated;
    };

    name = lib.mkDefault "ls-lint";
    description = "Check file and directory names with ls-lint";
    package = lib.mkDefault pkgs.ls-lint;
    entry = toString (pkgs.writeShellScript "ls-lint" ''
      set -euo pipefail
      cd "$(${pkgs.git}/bin/git rev-parse --show-toplevel)"
      exec ${config.package}/bin/ls_lint --config ${
        if cfg.configFile != null
        then lib.escapeShellArg cfg.configFile
        else cfg.generatedConfig
      }
    '');
    # ls-lint walks the whole tree, so a rename anywhere is checked against
    # every rule rather than only the staged paths.
    pass_filenames = false;
    always_run = lib.mkDefault true;
  };
}
